# MiniCRM cargo-deny配置
# 用于检查依赖的许可证、安全漏洞和重复依赖

[graph]
# 依赖图配置
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]
all-features = true

[output]
# 输出格式配置
feature-depth = 1

[advisories]
# 安全公告配置
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    # 在这里添加需要忽略的安全公告ID
    # "RUSTSEC-0000-0000",
]

[licenses]
# 许可证配置
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
deny = ["GPL-2.0", "GPL-3.0", "AGPL-1.0", "AGPL-3.0"]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    # 在这里添加许可证例外
    # { allow = ["GPL-3.0"], name = "some-gpl-crate" },
]

[[licenses.clarify]]
# 许可证澄清
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
# 禁用配置
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
    # 在这里添加允许的重复依赖
    # { name = "some-crate", version = "=0.1.0" },
]
deny = [
    # 在这里添加禁用的crate
    # { name = "openssl", version = "*" },
    # { name = "git2", version = "*" },
]
skip = [
    # 在这里添加跳过检查的crate
    # { name = "some-crate", version = "=0.1.0" },
]
skip-tree = [
    # 在这里添加跳过整个依赖树的crate
    # { name = "some-crate", version = "=0.1.0" },
]

[sources]
# 源配置
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
